name: Go CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: twitter_auth
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123321
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.6'

      - name: Install dependencies
        run: go mod download

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do # Retry up to 10 times
            nc -zv postgres 5432 && echo "PostgreSQL is ready" && break
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done

      - name: Set environment variables for testing
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: twitter_auth
          DB_USER: postgres
          DB_PASSWORD: 123321
        run: echo "Environment variables for testing set."

      - name: Run unit tests
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: twitter_auth
          DB_USER: postgres
          DB_PASSWORD: 123321
        run: go test -v ./...
